# Generated by Django 4.0.3 on 2022-04-12 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobusTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_text', models.CharField(max_length=2500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='globus_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
